# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 23:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundaccount',
            name='avglosingsequence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='currency',
            field=models.CharField(blank=True, choices=[('AUD', 'AUD'), ('GBP', 'GBP')], help_text='fund base currency', max_length=10),
        ),
        # migrations.AlterField(
        #     model_name='fundaccount',
        #     name='systems',
        #     field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), size=None), null=True, size=None),
        # ),
    ]
