# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 00:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_auto_20160329_2326'),
        ('funds', '0003_auto_20160329_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundaccount',
            name='systemslist',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='betamounts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='bfprices',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='dailybalances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='systems',
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='systems',
            field=models.ManyToManyField(to='systems.System'),
        ),
    ]
