# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 01:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_auto_20160330_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundaccount',
            old_name='wentLive',
            new_name='liveSince',
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='betamounts',
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='dailybalances',
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='bfcumtotalbalances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='bfenddaybalances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='bfstartdaybalances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='dailybfbalances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='dailycashoutbalances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='investments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='lratio',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='places',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='racedates',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='returns',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='sequences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
