# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_auto_20160330_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundaccount',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='description',
            field=models.CharField(blank=True, help_text='rationale', max_length=20),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='fundname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='fundaccount',
            unique_together=set([]),
        ),
    ]
