# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_auto_20160330_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundaccount',
            name='description',
            field=models.CharField(blank=True, help_text='rationale', max_length=50),
        ),
    ]
