# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_auto_20160330_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundaccount',
            name='fundname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='slug',
            field=models.SlugField(default=None, max_length=70, unique=True),
        ),
    ]
