# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='runtype',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('HISTORICAL', 'HISTORICAL')], default='HISTORICAL', help_text='live_or_historical', max_length=15),
        ),
        migrations.AlterField(
            model_name='system',
            name='systemtype',
            field=models.CharField(choices=[('tg', 'Trainglot'), ('mi', 'Metainvest'), ('custom', 'Custom'), ('other', 'Other')], default='tg', help_text='type: ', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='snapshottype',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('HISTORICAL', 'HISTORICAL')], default='HISTORICAL', help_text='initial(historical/live) ', max_length=15),
        ),
    ]
