# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 10:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20160327_0607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsnapshot',
            options={'get_latest_by': 'created', 'ordering': ('-levelbsprofitpc',)},
        ),
        migrations.AddField(
            model_name='system',
            name='exposure',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default='{}', help_text='parameters exposed to', size=None),
        ),
        migrations.AddField(
            model_name='system',
            name='query',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}', help_text='FS query params'),
        ),
        migrations.AddField(
            model_name='system',
            name='rpquery',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}', help_text='equivalent RP query params'),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='bluerows',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='greenrows',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='redrows',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='yearcolorcounts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='yearstats',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.TextField(help_text='rationale', null=True),
        ),
    ]
