# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 10:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20160329_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
