# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 23:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_runner_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='isLay',
            field=models.BooleanField(default=False, help_text='lay?'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='damname',
            field=models.CharField(help_text="Dam's name", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='damsirename',
            field=models.CharField(help_text="Dam's sire name", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='isplaced',
            field=models.NullBooleanField(help_text='Placed?'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='racetime',
            field=models.CharField(help_text='Race off time', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='exposure',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default='{}', help_text='exposure', size=None),
        ),
        migrations.AlterField(
            model_name='system',
            name='isActive',
            field=models.BooleanField(help_text='is the system an active system?'),
        ),
        migrations.AlterField(
            model_name='system',
            name='query',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='system',
            name='rpquery',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
    ]
